### ISSUE TITLE
Leader replacement doesn't work when leader is set to <space>

### ISSUE THREAD

**Issue by jan-xyz** [Cassin01/wf.nvim#102]
## Description

The leader replacement doesn't work when leader is set to 
```lua
vim.g.leadermap = " "
```
because space is represented as `<Space>` in the finder while the leader replacement is an actual space (` `). 

## Steps to reproduce

1. Set leader to space with `:lua vim.g.leadermap = " "`
1. Setup leader which-key with 
```lua
vim.keymap.set("n", "<Leader>",
				which_key({ text_insert_in_advance = "<Leader>"),
				{ noremap = true, silent = true, desc = "[wf.nvim] which-key /" }
			)
```
3. when performing the keymap notice that a space is inserted and the list is empty instead of inserting `<Space>`.

## Expected behavior

The space and leader behaviour should match so that the list is populated in the same way that the replacement work here.

## Environment

- Neovim version: 0.9.5
- wf version: latest
- Plugin clash: none

As a workaround I setup the keymap now as
```lua
vim.keymap.set("n", "<Leader>",
				which_key({ text_insert_in_advance = "<Space>"),
				{ noremap = true, silent = true, desc = "[wf.nvim] which-key /" }
			)
```
which works as it should I think, but I guess the nice way would be that it behaves the same in both?

**Comment by Cassin01** [comment]
Thank you for issuing!

**Comment by jan-xyz** [comment]
Thanks! I will give it a spin!

**Comment by jan-xyz** [comment]
it works!
