### ISSUE TITLE
<leader><Tab>  does not work

### ISSUE THREAD

**Issue by Miloas** [Cassin01/wf.nvim#105]
## Description

`<leader><Tab>` keymap does not work as expected in `wf.nvim`, when we input `<leader>` then input `<Tab>` after `wf.nvim`'s popup window showed.

## Steps to reproduce
1. Installing `wf.nvim` and then set keymap `<leader><Tab>` for something:
```
vim.keymap.set("n", "<leader><Tab>", "<C-^>", { desc = "switch to previous buffer" })
```
2. Input `<leader>` show the popup window:
<img width="598" alt="Screenshot 2024-01-07 at 00 02 28" src="https://github.com/Cassin01/wf.nvim/assets/11530682/11ad43a3-ef43-4865-b96a-0c9f9f494aaf">

3. Then input `<Tab>`

4. Nothing happened, seems like `<Tab>` cannot input in `wf.nvim`'s which key input window

## Expected behavior

If keymap is:
```
vim.keymap.set("n", "<leader><Tab>", "<C-^>", { desc = "switch to previous buffer" })
```
It should switch to previous buffer like we set.

## Environment

- Neovim version: Nightly
- wf version: latest
- Plugin clash: none

**Comment by Cassin01** [comment]
Thank you for issuing.
I can't check the work until the Jan-16 because I'm on the business trip. sorry for in convenience.

**Comment by Cassin01** [comment]
I have fixed the issue. If you think the bug is not fixed, please notify me. Thank you for noticing!

**Comment by Miloas** [comment]
> I have fixed the issue. If you think the bug is not fixed, please notify me. Thank you for noticing!

@Cassin01 Thanks for your fix, it works like a charm.

FYI, but my old config
```
vim.keymap.set(
  "n",
  "<leader>",
  which_key({ text_insert_in_advance = "<leader>", key_group_dict = _G.__key_prefixes["n"] })
)
```
seems borken.

When I input `<space>`:
![Screenshot 2024-01-21 at 21 54 54](https://github.com/Cassin01/wf.nvim/assets/11530682/5c7ec6cb-f4d5-4cf7-ac67-623b9ab4cd2b)

but this works (text_insert_in_advance = "`<leader>`" => text_insert_in_advance = "`<Space>`"):
```
vim.keymap.set(
  "n",
  "<leader>",
  which_key({ text_insert_in_advance = "<Space>", key_group_dict = _G.__key_prefixes["n"] })
)
```

I dont know this is feature or bug or my config error, thanks

**Comment by Cassin01** [comment]
@Miloas Thank you for noticing. I have add support for lowercase <Leader>.
