### ISSUE TITLE
Minimal setup Bookmark gives an error (not an editor command: IndentBlanklineRefresh) on startup

### ISSUE THREAD

**Issue by mBaratta96** [Cassin01/wf.nvim#85]
## Description

Coping and pasting the minimal setup in a specific configuration file creates the following error message on Neovim startup:

```
Errore/i eseguendo /home/marco/.config/nvim/init.lua..CursorMoved Autocommands for "*":
E492: Non è un comando dell'editor: IndentBlanklineRefresh
Errore/i eseguendo /home/marco/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        /home/marco/.config/nvim/lua/confs/keys.lua:18: in main chunk
        [C]: in function 'require'
        /home/marco/.config/nvim/lua/plugins.lua:106: in main chunk
        [C]: in function 'require'
        /home/marco/.config/nvim/init.lua:3: in main chunk
```

This breaks the entire configuration.

If I comment all the `Bookmark` section, the plugin works.

## Steps to reproduce

1. Create a `keys.lua` file
2. Copy and paste the minimal setup in `keys.lua`
3. Load the file with `require('confs.keys')`
4. Restart Neovim.

## Expected behavior

Neovim loads correctly even with the `Bookmark` section of the minimal setup-

## Environment

- Neovim version: 0.9.0
- wf version: latest

**Comment by Cassin01** [comment]
The comma following `buffer()` was missing in the following section of the miniamal setup. I think it will work if you fix this.
Thank you for pointing this out.


```
vim.keymap.set(
  "n",
  "<Space>wbu",
  -- buffer(opts?: table) -> function
  -- opts?: option
  buffer(), <- here
  {noremap = true, silent = true, desc = "[wf.nvim] buffer"}
)
```
