### ISSUE TITLE
invalid key: title in function 'open_win'

### ISSUE THREAD

**Issue by falcomomo** [Cassin01/wf.nvim#90]
## Description

Installed using the packer.nvim script given (stable version), and get this error on any action which triggers wf - eg. <leader>wbu, or <leader>wr, or <leader> pause.

## Steps to reproduce

1. Make any wf command - eg. <leader>wr
2. Get a stacktrace
3. ![image](https://user-images.githubusercontent.com/7228235/236155138-9021a1a1-41e1-4801-878e-ebda3d40dab2.png)

## Expected behavior

Expect the wf pop-up to load

## Environment

- Neovim version: 0.8.3
- wf version: latest stable
- Plugin clash: Following is a list of plugins I have:

-  • LuaSnip
-  • auto-pairs
-  • cellular-automaton.nvim
-  • cloak.nvim
-  • cmp-buffer
-  • cmp-nvim-lsp
-  • cmp-nvim-lua
-  • cmp-path
-  • cmp_luasnip
-  • copilot.vim
-  • dracula.nvim
-  • friendly-snippets
-  • harpoon
-  • indent-blankline.nvim
-  • legendary.nvim
-  • lsp-zero.nvim
-  • lualine.nvim
-  • mason-lspconfig.nvim
-  • mason.nvim
-  • nerdcommenter
-  • nui.nvim
-  • nvim-cmp
-  • nvim-lspconfig
-  • nvim-navbuddy
-  • nvim-navic
-  • nvim-treesitter
-  • nvim-treesitter-context
-  • nvim-web-devicons (not loaded)
-  • packer.nvim
-  • playground
-  • plenary.nvim
-  • refactoring.nvim
-  • telescope-fzf-native.nvim
-  • telescope.nvim
-  • trouble.nvim
-  • undotree
-  • vim-fugitive
-  • vim-merginal
-  • vim-visual-multi
-  • wf.nvim
-  • which-key.nvim
-  • zen-mode.nvim

**Comment by Cassin01** [comment]
Fix to disallow use of `title` in neovim versions lower than v0.9.0.
This is because `title` in `nvim_open_win({buffer}, {enter}, {*config})` is unstable in neovim version 0.8 and the behavior when `title` is used is not stable.
